# Generated by Django 2.0.5 on 2018-05-12 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='setup_time',
            field=models.DateField(default=datetime.datetime(2018, 5, 12, 22, 14, 40, 281161)),
        ),
        migrations.AlterField(
            model_name='identity',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2018, 5, 12, 22, 14, 40, 270668)),
        ),
        migrations.AlterUniqueTogether(
            name='loginlog',
            unique_together={('acc_id', 'login_time')},
        ),
        migrations.AlterUniqueTogether(
            name='logoutlog',
            unique_together={('acc_id', 'logout_time')},
        ),
    ]
