# Generated by Django 2.0.5 on 2018-05-12 22:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vbank', '0002_auto_20180512_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='setup_time',
            field=models.DateField(default=datetime.datetime(2018, 5, 12, 22, 15, 53, 887398)),
        ),
        migrations.AlterField(
            model_name='identity',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2018, 5, 12, 22, 15, 53, 877372)),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='acc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbank.Account'),
        ),
        migrations.AlterField(
            model_name='logoutlog',
            name='acc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbank.Account'),
        ),
    ]
