# Generated by Django 2.0.5 on 2018-05-13 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbank', '0003_auto_20180512_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='setup_time',
            field=models.DateField(default=datetime.datetime(2018, 5, 13, 0, 44, 0, 637645)),
        ),
        migrations.AlterField(
            model_name='flow',
            name='d_account',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='flow',
            name='d_bankcard',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='flow',
            name='s_account',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='flow',
            name='s_bankcard',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='identity',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2018, 5, 13, 0, 44, 0, 627117)),
        ),
    ]
