# Generated by Django 2.0.5 on 2018-05-13 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbank', '0004_auto_20180513_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='setup_time',
            field=models.DateField(default=datetime.datetime(2018, 5, 13, 0, 44, 10, 518549)),
        ),
        migrations.AlterField(
            model_name='identity',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2018, 5, 13, 0, 44, 10, 508494)),
        ),
    ]
