# Generated by Django 2.0.5 on 2018-05-13 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbank', '0006_auto_20180513_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewBankcard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_num', models.CharField(max_length=19)),
                ('regist_time', models.DateTimeField()),
                ('bbname', models.CharField(max_length=32)),
                ('card_type', models.IntegerField()),
            ],
            options={
                'db_table': 'view_bankcard',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='loginlog',
            name='login_status',
            field=models.IntegerField(choices=[(1, '登陆成功'), (2, '登陆失败')], default=1),
        ),
        migrations.AlterField(
            model_name='bank',
            name='setup_time',
            field=models.DateField(default=datetime.datetime(2018, 5, 13, 13, 51, 49, 701740)),
        ),
        migrations.AlterField(
            model_name='identity',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2018, 5, 13, 13, 51, 49, 691713)),
        ),
    ]
